### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'tensor_type'

### ISSUE THREAD

**Issue by hsluoyz** [prakashpandey9/Text-Classification-Pytorch#8]
Running the ``main.py`` got the error:

```
C:\Python36\python.exe I:/github_repos/Text-Classification-Pytorch/main.py
Traceback (most recent call last):
  File "I:/github_repos/Text-Classification-Pytorch/main.py", line 11, in <module>
    TEXT, vocab_size, word_embeddings, train_iter, valid_iter, test_iter = load_data.load_dataset()
  File "I:\github_repos\Text-Classification-Pytorch\load_data.py", line 31, in load_dataset
    LABEL = data.LabelField(tensor_type=torch.FloatTensor)
  File "C:\Python36\lib\site-packages\torchtext\data\field.py", line 699, in __init__
    super(LabelField, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'tensor_type'

Process finished with exit code 1
```

**Comment by fmehralian** [comment]
In load_data.py, remove the argument of LabelField in line 31:
`LABEL = data.LabelField()`

**Comment by zhangxiaowbl** [comment]
Running the main.py got the error:

module 'torchtext.data' has no attribute 'LabelField'. Could you help please, Thanks!
